services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db_data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  db_data: