create table roles
(
    id   bigint generated by default as identity
        primary key,
    role varchar(255) not null
        constraint ukg50w4r0ru3g9uf6i6fr4kpro8
            unique
);

alter table roles
    owner to egguard_user;

create table users
(
    id        bigint generated by default as identity
        primary key,
    address   varchar(255),
    city      varchar(255),
    country   varchar(255),
    email     varchar(255) not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    name      varchar(255) not null,
    phone     varchar(255)
        constraint ukdu5v5sr43g5bfnji4vb8hg5s3
            unique,
    photo_url varchar(255),
    surnames  varchar(255) not null,
    zip       varchar(255),
    role_id   bigint       not null
        constraint fkp56c1712k691lhsyewcssf40f
            references roles
);

alter table users
    owner to egguard_user;

create table farms
(
    id        bigint generated by default as identity
        primary key,
    latitude  double precision not null,
    longitude double precision not null,
    name      varchar(255)     not null,
    photo_url varchar(255),
    user_id   bigint           not null
        constraint fkm4yq5qagd4lwf6qournyqckrf
            references users
);

alter table farms
    owner to egguard_user;

create table eggs
(
    id        bigint generated by default as identity
        primary key,
    broken    boolean          not null,
    coord_x   double precision not null,
    coord_y   double precision not null,
    picked    boolean          not null,
    timestamp timestamp(6)     not null,
    farm_id   bigint           not null
        constraint fk4xrolxwdndk15w030np1a3w93
            references farms
);

alter table eggs
    owner to egguard_user;

create table notifications
(
    id        bigint generated by default as identity
        primary key,
    message   varchar(1000) not null,
    photo_url varchar(255),
    severity  varchar(255)  not null
        constraint notifications_severity_check
            check ((severity)::text = ANY
        ((ARRAY ['INFO'::character varying, 'WARNING'::character varying, 'CRITICAL'::character varying])::text[])),
    timestamp timestamp(6)  not null,
    farm_id   bigint        not null
        constraint fk8plhs7wdyeo9o3nxg4j4qn078
            references farms
);

alter table notifications
    owner to egguard_user;

create table robots
(
    id            bigint generated by default as identity
        primary key,
    purchase_date timestamp(6),
    status        varchar(255) not null
        constraint robots_status_check
            check ((status)::text = ANY
        ((ARRAY ['ACTIVE'::character varying, 'INACTIVE'::character varying, 'MAINTENANCE'::character varying, 'ERROR'::character varying])::text[])),
    farm_id       bigint       not null
        constraint fka74dlmhsmd4dhu6e92upf2wuv
            references farms
);

alter table robots
    owner to egguard_user;

